import { CommunityWorkflow } from './communityTypes';

export const OFFICIAL_TEMPLATES: CommunityWorkflow[] = [
  {
    id: 'template-feature-branch',
    slug: 'feature-branch-workflow',
    title: 'Feature Branch Workflow',
    description: 'Standard, isolated feature development pipeline from local working changes to remote pull request staging.',
    category: 'feature',
    visibility: 'public',
    author: {
      login: 'branchwatch',
      name: 'BranchWatch Team',
      avatar_url: 'https://avatars.githubusercontent.com/u/9919?s=200&v=4',
      isVerified: true,
    },
    version: 'v1.2',
    forksCount: 142,
    starsCount: 384,
    usageCount: 2450,
    tags: ['git-flow', 'feature-branch', 'best-practices', 'github'],
    isFeatured: true,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-18T14:30:00Z',
    educationalNotes: {
      'node-wt': {
        title: 'Inspect Working Tree',
        explanation: 'Inspect uncommitted files and verify only intended changes exist before staging.',
        command: 'git status',
        bestPracticeTip: 'Always check git status or git diff before staging to avoid tracking .env or secrets.',
      },
      'node-stage': {
        title: 'Stage Changes Selectively',
        explanation: 'Stage your modified source files into the Git index preparing them for atomic commit.',
        command: 'git add .',
        bestPracticeTip: 'Keep commits focused on a single responsibility instead of staging everything at once.',
      },
      'node-commit': {
        title: 'Create Atomic Commit',
        explanation: 'Record staged changes with a clear, imperative commit message following conventional commits format.',
        command: 'git commit -m "feat(ui): add visual workflow canvas"',
        bestPracticeTip: 'Write concise commit titles under 72 characters explaining what changed and why.',
      },
      'node-branch': {
        title: 'Create Topic Branch',
        explanation: 'Isolate work onto a dedicated feature branch to keep main branch deployable and clean.',
        command: 'git switch -c feature/visual-canvas',
        bestPracticeTip: 'Prefix branch names with categories (e.g. feature/, bugfix/, hotfix/).',
      },
      'node-push': {
        title: 'Push Upstream',
        explanation: 'Publish branch commits to the remote origin with upstream tracking configuration.',
        command: 'git push -u origin feature/visual-canvas',
        bestPracticeTip: 'Always verify target remote branch name before pushing to shared origins.',
      },
    },
    nodes: [
      {
        id: 'node-wt',
        type: 'working_tree',
        title: 'Working Tree',
        x: 60,
        y: 180,
        status: 'ready',
        config: { filesChangedCount: 3, additions: 84, deletions: 12 },
      },
      {
        id: 'node-stage',
        type: 'stage',
        title: 'Stage',
        x: 340,
        y: 180,
        status: 'draft',
        config: { selectedFiles: ['src/components/Canvas.tsx', 'src/lib/types.ts'] },
      },
      {
        id: 'node-commit',
        type: 'commit',
        title: 'Commit',
        x: 620,
        y: 180,
        status: 'draft',
        config: { commitMessage: 'feat: implement interactive node canvas' },
      },
      {
        id: 'node-branch',
        type: 'branch',
        title: 'Branch',
        x: 900,
        y: 180,
        status: 'draft',
        config: { branchName: 'feature/canvas-engine' },
      },
      {
        id: 'node-push',
        type: 'push',
        title: 'Push Upstream',
        x: 1180,
        y: 180,
        status: 'draft',
        config: { remoteName: 'origin', branchName: 'feature/canvas-engine' },
      },
    ],
    connections: [
      { id: 'c1', fromId: 'node-wt', toId: 'node-stage' },
      { id: 'c2', fromId: 'node-stage', toId: 'node-commit' },
      { id: 'c3', fromId: 'node-commit', toId: 'node-branch' },
      { id: 'c4', fromId: 'node-branch', toId: 'node-push' },
    ],
  },
  {
    id: 'template-hotfix',
    slug: 'hotfix-production-patch',
    title: 'Hotfix & Emergency Patch',
    description: 'Fast-path pipeline to branch off main, apply a targeted bugfix, and push directly for emergency CI deployment.',
    category: 'hotfix',
    visibility: 'public',
    author: {
      login: 'alex_dev',
      name: 'Alex Rivera',
      avatar_url: 'https://avatars.githubusercontent.com/u/1024025?v=4',
    },
    version: 'v2.0',
    forksCount: 96,
    starsCount: 275,
    usageCount: 1820,
    tags: ['hotfix', 'emergency', 'production', 'patch'],
    isFeatured: true,
    createdAt: '2026-08-25T08:15:00Z',
    updatedAt: '2026-09-12T11:00:00Z',
    educationalNotes: {
      'node-branch': {
        title: 'Branch off Main/Production',
        explanation: 'Branch directly from latest verified production commit to avoid picking up unreleased development work.',
        command: 'git switch -c hotfix/auth-token-patch main',
        bestPracticeTip: 'Never base hotfixes on unmerged staging branches.',
      },
      'node-commit': {
        title: 'Targeted Fix Commit',
        explanation: 'Only commit the minimal lines of code needed to fix the regression.',
        command: 'git commit -m "fix(auth): prevent session cookie expiry on redirect"',
        bestPracticeTip: 'Do not bundle cosmetic refactors with emergency production patches.',
      },
    },
    nodes: [
      {
        id: 'node-branch',
        type: 'branch',
        title: 'Hotfix Branch',
        x: 60,
        y: 180,
        status: 'ready',
        config: { branchName: 'hotfix/cookie-patch' },
      },
      {
        id: 'node-wt',
        type: 'working_tree',
        title: 'Working Tree',
        x: 340,
        y: 180,
        status: 'ready',
        config: { filesChangedCount: 1, additions: 4, deletions: 2 },
      },
      {
        id: 'node-stage',
        type: 'stage',
        title: 'Stage',
        x: 620,
        y: 180,
        status: 'draft',
        config: { selectedFiles: ['src/app/api/auth/session/route.ts'] },
      },
      {
        id: 'node-commit',
        type: 'commit',
        title: 'Commit Fix',
        x: 900,
        y: 180,
        status: 'draft',
        config: { commitMessage: 'fix(auth): correct cookie maxAge handling' },
      },
      {
        id: 'node-push',
        type: 'push',
        title: 'Push Hotfix',
        x: 1180,
        y: 180,
        status: 'draft',
        config: { remoteName: 'origin', branchName: 'hotfix/cookie-patch' },
      },
    ],
    connections: [
      { id: 'c1', fromId: 'node-branch', toId: 'node-wt' },
      { id: 'c2', fromId: 'node-wt', toId: 'node-stage' },
      { id: 'c3', fromId: 'node-stage', toId: 'node-commit' },
      { id: 'c4', fromId: 'node-commit', toId: 'node-push' },
    ],
  },
  {
    id: 'template-opensource-pr',
    slug: 'opensource-pr-contribution',
    title: 'Open Source PR Contribution Flow',
    description: 'Clean workflow for pulling upstream updates into local fork, creating topic branch, and pushing for Pull Request submission.',
    category: 'opensource',
    visibility: 'public',
    author: {
      login: 'sarah_codes',
      name: 'Sarah Chen',
      avatar_url: 'https://avatars.githubusercontent.com/u/59203?v=4',
    },
    version: 'v1.0',
    forksCount: 68,
    starsCount: 198,
    usageCount: 1120,
    tags: ['opensource', 'fork', 'pull-request', 'github'],
    createdAt: '2026-09-01T12:00:00Z',
    updatedAt: '2026-09-15T16:20:00Z',
    nodes: [
      {
        id: 'node-pull',
        type: 'pull',
        title: 'Sync Upstream',
        x: 60,
        y: 180,
        status: 'ready',
        config: { remoteName: 'upstream', branchName: 'main' },
      },
      {
        id: 'node-branch',
        type: 'branch',
        title: 'Topic Branch',
        x: 340,
        y: 180,
        status: 'draft',
        config: { branchName: 'contrib/theme-tokens' },
      },
      {
        id: 'node-stage',
        type: 'stage',
        title: 'Stage Changes',
        x: 620,
        y: 180,
        status: 'draft',
        config: { selectedFiles: ['README.md', 'src/theme.css'] },
      },
      {
        id: 'node-commit',
        type: 'commit',
        title: 'Descriptive Commit',
        x: 900,
        y: 180,
        status: 'draft',
        config: { commitMessage: 'docs(readme): clarify theme token overrides' },
      },
      {
        id: 'node-push',
        type: 'push',
        title: 'Push to Fork',
        x: 1180,
        y: 180,
        status: 'draft',
        config: { remoteName: 'origin', branchName: 'contrib/theme-tokens' },
      },
    ],
    connections: [
      { id: 'c1', fromId: 'node-pull', toId: 'node-branch' },
      { id: 'c2', fromId: 'node-branch', toId: 'node-stage' },
      { id: 'c3', fromId: 'node-stage', toId: 'node-commit' },
      { id: 'c4', fromId: 'node-commit', toId: 'node-push' },
    ],
  },
  {
    id: 'template-monorepo-release',
    slug: 'monorepo-scoped-release',
    title: 'Monorepo Package Release',
    description: 'Scoped package release flow: stages specific workspace directory, generates tagged version commit, and pushes to remote.',
    category: 'monorepo',
    visibility: 'public',
    author: {
      login: 'david_k',
      name: 'David Kim',
      avatar_url: 'https://avatars.githubusercontent.com/u/148201?v=4',
    },
    version: 'v1.4',
    forksCount: 44,
    starsCount: 165,
    usageCount: 890,
    tags: ['monorepo', 'pnpm', 'turborepo', 'release'],
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-17T10:15:00Z',
    nodes: [
      {
        id: 'node-wt',
        type: 'working_tree',
        title: 'Working Tree',
        x: 60,
        y: 180,
        status: 'ready',
        config: { filesChangedCount: 4, additions: 62, deletions: 8 },
      },
      {
        id: 'node-stage',
        type: 'stage',
        title: 'Stage Package',
        x: 340,
        y: 180,
        status: 'draft',
        config: { selectedFiles: ['packages/ui/package.json', 'packages/ui/src/index.ts'] },
      },
      {
        id: 'node-commit',
        type: 'commit',
        title: 'Version Commit',
        x: 620,
        y: 180,
        status: 'draft',
        config: { commitMessage: 'chore(release): @branchwatch/ui@1.4.0' },
      },
      {
        id: 'node-push',
        type: 'push',
        title: 'Push Release',
        x: 900,
        y: 180,
        status: 'draft',
        config: { remoteName: 'origin', branchName: 'main' },
      },
    ],
    connections: [
      { id: 'c1', fromId: 'node-wt', toId: 'node-stage' },
      { id: 'c2', fromId: 'node-stage', toId: 'node-commit' },
      { id: 'c3', fromId: 'node-commit', toId: 'node-push' },
    ],
  },
  {
    id: 'template-clean-rebase',
    slug: 'clean-rebase-sync',
    title: 'Clean Rebase & Remote Sync',
    description: 'Pulls latest upstream commits and rebases feature branch to maintain a linear, bisect-friendly commit history.',
    category: 'basics',
    visibility: 'public',
    author: {
      login: 'elena_v',
      name: 'Elena Vance',
      avatar_url: 'https://avatars.githubusercontent.com/u/84291?v=4',
    },
    version: 'v1.0',
    forksCount: 52,
    starsCount: 142,
    usageCount: 930,
    tags: ['rebase', 'linear-history', 'sync', 'git-basics'],
    createdAt: '2026-09-08T14:00:00Z',
    updatedAt: '2026-09-19T09:40:00Z',
    nodes: [
      {
        id: 'node-pull',
        type: 'pull',
        title: 'Fetch Remote',
        x: 60,
        y: 180,
        status: 'ready',
        config: { remoteName: 'origin', branchName: 'main' },
      },
      {
        id: 'node-branch',
        type: 'branch',
        title: 'Feature Branch',
        x: 340,
        y: 180,
        status: 'draft',
        config: { branchName: 'feature/auth-guard' },
      },
      {
        id: 'node-push',
        type: 'push',
        title: 'Force-with-lease Push',
        x: 620,
        y: 180,
        status: 'draft',
        config: { remoteName: 'origin', branchName: 'feature/auth-guard' },
      },
    ],
    connections: [
      { id: 'c1', fromId: 'node-pull', toId: 'node-branch' },
      { id: 'c2', fromId: 'node-branch', toId: 'node-push' },
    ],
  },
];
